### ISSUE TITLE
add custom DNS records

### ISSUE THREAD

**Issue by vespino** [klutchell/unbound-docker#126]
I created a Docker container using the following docker-compose.yml:

```
services:
  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    network_mode: bridge
    ports:
      - '5335:53/tcp'
      - '5335:53/udp'
    restart: always
    volumes:
      - ./a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
```

First of all I'm using Unbound as an upstream server for Pi-hole but I was thinking why not remove Pi-hole? For this I would have to move my blocklists and custom records to Unbound which in theory sounds very simple, just add the records to "a-records.conf", right? I added a custom record like so:

`local-data: "canon.hanscees.com A 192.168.0.60"`

After rebuilding the container though, I'm not able to ping this record. Is this the right way to do this?

Another question: would I have to restart Unbound every time the list changes?
