### ISSUE TITLE
Custom port being ignored since update to v1.19.1

### ISSUE THREAD

**Issue by NG1973** [klutchell/unbound-docker#350]
I use unbound with PiHole, therefore I have a custom .conf file specifying port 5335 for use by unbound. This has been working without issue. However, since updating the docker container from unbound version 1.19.0 to 1.19.1 at the weekend the custom port is ignored and unbound fails to start due to not being able to bind port 53.

Specifying v1.19.0 in the docker compose file rather than latest has my setup back running as before.

**Comment by klutchell** [comment]
Can you share the relevant bits of your custom.conf and how you are mounting it?

It sounds similar to the same issue we discussed [here](https://github.com/klutchell/unbound-docker/issues/221) so I would suggest reading through that thread for suggestions as well.

**Comment by NG1973** [comment]
Thank you for your quick response. Apologies for missing that previously closed issue. It is interesting to read in your linked thread that the order of interface and port is important - this could be my issue (as you can see below, I specify port after interface), I will have play around after work.

The top of my custom .conf file:

```
server:
verbosity: 0

interface: 127.0.0.1
port: 5335

do-ip4: yes
do-ip6: yes
do-udp: yes
do-tcp: yes
prefer-ip6: yes
```

My docker-compose.yml:

```
unbound:
    container_name: unbound
    image: klutchell/unbound
    hostname: unbound
    network_mode: "host"
    volumes:
      - ./unbound.d:/etc/unbound/custom.conf.d
    restart: 'unless-stopped'
```

**Comment by NG1973** [comment]
I still can't get this to work. However, I now suspect that it is an issue with my Docker setup as Pi-Hole is no longer saving to or reading from config files either (I hadn't realised this until I updated the container yesterday).

I will investigate this.

Apologies for the noise.

**Comment by wlhlm** [comment]
I just wanted to report that I stumbled upon the same issue. I have a similar setup with pi-hole behind unbound, though bound together with a podman pod rather than docker-compose. Upgrading the unbound container to 1.19.1, I hit the same issue where unbound suddenly began binding to port 53. Here is all of my custom config:

```
server:
    port: 5354

# RFC 8806
auth-zone:
    name: "."
    master: "b.root-servers.net"
    master: "c.root-servers.net"
    master: "d.root-servers.net"
    master: "f.root-servers.net"
    master: "g.root-servers.net"
    master: "k.root-servers.net"
    fallback-enabled: yes
    for-downstream: no
    for-upstream: yes
    url: "https://www.internic.net/domain/root.zone"
    zonefile: "root.zone"
```
The idea is to have unbound only run on 127.0.0.1, port 5354

Downgrading the container to [1.19.0](https://hub.docker.com/layers/klutchell/unbound/1.19.0/images/sha256-7a752756eb6ca4a90213db4beaf0b829986b4ce59ae8e998966d5221a474381d) fixes the issue.

Reading through #221, the suggested change for [1.19.1](https://hub.docker.com/layers/klutchell/unbound/1.19.1/images/sha256-8d12b6738b1642b8d82df7b8e86254f53da0b97170f534ff2f602a4716468945) is to use the `interface` directive. So I changed it to the following:
```
server:
    interface: 127.0.0.1@5354

# rest of config see above
```
While this makes unbound open a listening socket on 127.0.0.1:5354, it keeps 0.0.0.0:53 open as well, which I don't want as it conflicts with pi-hole:
```
# ss -tuln
Netid            State             Recv-Q            Send-Q                       Local Address:Port                       Peer Address:Port           Process
udp              UNCONN            0                 0                                  0.0.0.0:53                              0.0.0.0:*
udp              UNCONN            0                 0                                127.0.0.1:5354                            0.0.0.0:*
tcp              LISTEN            0                 256                              127.0.0.1:5354                            0.0.0.0:*
tcp              LISTEN            0                 256                                0.0.0.0:53                              0.0.0.0:*
```

If I'm reading this [comment](https://github.com/klutchell/unbound-docker/issues/221#issuecomment-1809373304) correctly, then there is no way to stop unbound from listening on 0.0.0.0 (and port 53) via the custom config file. Is there another workaround?
