### ISSUE TITLE
Container constantly restart on version 1.14+

### ISSUE THREAD

**Issue by TheNamelessWonderer** [klutchell/unbound-docker#36]
On versions 1.14+ the container always restarts. This doesn't happen on 1.13.2-rev-2.
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
uname -a
Linux raspberrypi 5.10.0-10-arm64 #1 SMP Debian 5.10.84-1 (2021-12-08) aarch64 GNU/Linux
```
```
sudo docker info
[sudo] password for user: 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-10-arm64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 906.5MiB
 Name: raspberrypi
 ID: ATF5:3DNG:2LYT:E6O7:CQQ6:MN2Y:3JFG:4PVB:3CSB:6FS2:36U7:3H47
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
```
sudo docker pull --platform linux/arm/v7 klutchell/unbound:v1.14.0-r4
v1.14.0-r4: Pulling from klutchell/unbound
3d6f283fe4fa: Pull complete 
Digest: sha256:642c667463ff2177c8f7954b7f3b805916b86b31da693b8c2ef39742dce0474f
Status: Downloaded newer image for klutchell/unbound:v1.14.0-r4
WARNING: image with reference klutchell/unbound was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/arm64
docker.io/klutchell/unbound:v1.14.0-r4
```
```
sudo docker run --rm -it klutchell/unbound:v1.14.0-r4 -v -v
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[1640531835] unbound[1:0] notice: Start of unbound 1.14.0.
[1640531835] unbound[1:0] debug: chdir to /etc/unbound
[1640531835] unbound[1:0] debug: drop user privileges, run as unbound
[1640531835] unbound[1:0] debug: switching log to stderr
[1640531835] unbound[1:0] debug: module config: "validator iterator"
[1640531835] unbound[1:0] notice: init module 0: validator
[1640531835] unbound[1:0] notice: init module 1: iterator
[1640531835] unbound[1:0] debug: target fetch policy for level 0 is 3
[1640531835] unbound[1:0] debug: target fetch policy for level 1 is 2
[1640531835] unbound[1:0] debug: target fetch policy for level 2 is 1
[1640531835] unbound[1:0] debug: target fetch policy for level 3 is 0
[1640531835] unbound[1:0] debug: target fetch policy for level 4 is 0
[1640531835] unbound[1:0] debug: Reading root hints from /etc/unbound/root.hints
[1640531835] unbound[1:0] info: DelegationPoint<.>: 13 names (0 missing), 26 addrs (0 result, 26 avail) parentNS
[1640531835] unbound[1:0] debug: cache memory msg=33040 rrset=33040 infra=3920 val=33200
[1640531835] unbound[1:0] info: start of service (unbound 1.14.0).
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_state_initial event:module_event_new
[1640531835] unbound[1:0] info: validator operate: query . DNSKEY IN
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1640531835] unbound[1:0] info: resolving . DNSKEY IN
[1640531835] unbound[1:0] info: priming . IN NS
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1640531835] unbound[1:0] info: iterator operate: query . NS IN
[1640531835] unbound[1:0] info: processQueryTargets: . NS IN
[1640531835] unbound[1:0] info: sending query: . NS IN
[1640531835] unbound[1:0] debug: sending to target: <.> 192.36.148.17#53
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_wait_reply event:module_event_reply
[1640531835] unbound[1:0] info: iterator operate: query . NS IN
[1640531835] unbound[1:0] info: response for . NS IN
[1640531835] unbound[1:0] info: reply from <.> 192.36.148.17#53
[1640531835] unbound[1:0] info: query response was ANSWER
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_state_initial event:module_event_moddone
[1640531835] unbound[1:0] info: validator operate: query . NS IN
[1640531835] unbound[1:0] info: priming successful for . NS IN
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_wait_subquery event:module_event_pass
[1640531835] unbound[1:0] info: iterator operate: query . DNSKEY IN
[1640531835] unbound[1:0] info: resolving (init part 2):  . DNSKEY IN
[1640531835] unbound[1:0] info: resolving (init part 3):  . DNSKEY IN
[1640531835] unbound[1:0] info: processQueryTargets: . DNSKEY IN
[1640531835] unbound[1:0] info: sending query: . DNSKEY IN
[1640531835] unbound[1:0] debug: sending to target: <.> 192.33.4.12#53
[1640531835] unbound[1:0] debug: cache memory msg=33709 rrset=38532 infra=4394 val=33200
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_wait_reply event:module_event_reply
[1640531835] unbound[1:0] info: iterator operate: query . DNSKEY IN
[1640531835] unbound[1:0] info: response for . DNSKEY IN
[1640531835] unbound[1:0] info: reply from <.> 192.33.4.12#53
[1640531835] unbound[1:0] info: query response was ANSWER
[1640531835] unbound[1:0] info: finishing processing for . DNSKEY IN
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1640531835] unbound[1:0] info: validator operate: query . DNSKEY IN
[1640531835] unbound[1:0] info: prime trust anchor
[1640531835] unbound[1:0] info: generate keytag query _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_state_initial event:module_event_pass
[1640531835] unbound[1:0] info: validator operate: query . DNSKEY IN
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1640531835] unbound[1:0] info: resolving . DNSKEY IN
[1640531835] unbound[1:0] info: finishing processing for . DNSKEY IN
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1640531835] unbound[1:0] info: validator operate: query . DNSKEY IN
[1640531835] unbound[1:0] info: validate keys with anchor(DS): sec_status_secure
[1640531835] unbound[1:0] info: Successfully primed trust anchor . DNSKEY IN
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_state_initial event:module_event_pass
[1640531835] unbound[1:0] info: validator operate: query _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
[1640531835] unbound[1:0] info: resolving _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] info: resolving (init part 2):  _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] info: resolving (init part 3):  _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] info: processQueryTargets: _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] info: sending query: _ta-4a5c-4f66. A IN
[1640531835] unbound[1:0] debug: sending to target: <.> 199.7.91.13#53
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_wait_subquery event:module_event_pass
[1640531835] unbound[1:0] info: validator operate: query . DNSKEY IN
[1640531835] unbound[1:0] info: validate(positive): sec_status_secure
[1640531835] unbound[1:0] info: validation success . DNSKEY IN
[1640531835] unbound[1:0] debug: cache memory msg=33858 rrset=39800 infra=4631 val=34480
[1640531835] unbound[1:0] debug: iterator[module 1] operate: extstate:module_wait_reply event:module_event_reply
[1640531835] unbound[1:0] info: iterator operate: query _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] info: response for _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] info: reply from <.> 199.7.91.13#53
[1640531835] unbound[1:0] info: query response was NXDOMAIN ANSWER
[1640531835] unbound[1:0] info: finishing processing for _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] debug: validator[module 0] operate: extstate:module_wait_module event:module_event_moddone
[1640531835] unbound[1:0] info: validator operate: query _ta-4a5c-4f66. NULL IN
[1640531835] unbound[1:0] debug: cache memory msg=34041 rrset=40758 infra=4631 val=34480
```
```
version: "3"

networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/16

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    hostname: raspberrypi
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: ''
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      dns_net:
        ipv4_address: 172.20.0.6
    dns: 127.0.0.1
    restart: unless-stopped

  unbound:
    container_name: unbound
    hostname: unbound
    image: klutchell/unbound
    volumes:
    - /home/user/pihole/unbound:/etc/unbound
    ports:
    - "5335:5335/tcp"
    - "5335:5335/udp"
    networks:
      dns_net:
        ipv4_address: 172.20.0.7
    restart: unless-stopped
```
```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 5

    access-control: 172.16.0.0/12 allow
    access-control: 172.20.0.0/12 allow
    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow
    interface: 0.0.0.0
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # Suggested by the unbound man page to reduce fragmentation reassembly problems
    edns-buffer-size: 1472

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
```
I have switched it to 5 and I have the following log:
```
[1640533667] unbound[1:0] debug: creating tcp4 socket 0.0.0.0 5335
[1640533667] unbound[1:0] debug: switching log to syslog
[1640533720] unbound[1:0] debug: creating udp4 socket 0.0.0.0 5335
[1640533720] unbound[1:0] warning: so-rcvbuf 1048576 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
[1640533720] unbound[1:0] debug: creating tcp4 socket 0.0.0.0 5335
[1640533720] unbound[1:0] debug: switching log to syslog
```
I have put the root.hints in the unbound folder and unbound.conf has the pihole configuration in it. This works fine on 1-13-2-rev2 but just restarts on anything newer.
