### ISSUE TITLE
Could not open logfile ... No such file or directory

### ISSUE THREAD

**Issue by DragonQ** [klutchell/unbound-docker#460]
I feel a bit stupid asking this because it feels like I've done something very silly for this not to work. In my `/etc/unbound.conf` file I have this line:

`logfile: /var/log/unbound.log`

In my `docker-compose.yaml` I have this:

```
unbound:
  container_name: unbound
  image: 'klutchell/unbound:latest'
  restart: unless-stopped
  cap_add:
    - NET_ADMIN
  networks:
    pihole-net:
      ipv4_address: ${UNBOUND_IP}
  volumes:
    - ${UNBOUND_ROOT_PATH}/etc:/etc/unbound
    - ${UNBOUND_ROOT_PATH}/log/unbound.log:/var/log/unbound.log:rw
```

In my `.env` file I have this:

```
UNBOUND_IP=172.18.0.101
UNBOUND_ROOT_PATH=/home/user/docker/pihole/unbound
```

And yet, when unbound starts, the docker log contains this line and nothing gets written to my `/home/user/docker/pihole/unbound/log/unbound.log` file:

`[1718797901] unbound[1:0] error: Could not open logfile /var/log/unbound.log: No such file or directory`

Everything else seems to be working perfectly and it clearly knows where the log file is _meant_ to be (meaning my `etc` directory is being mounted correctly), it just doesn't seem to think the mounted log file exists. I've tried giving the file 666 permissions on the host and chown'd it to `101:102` to no avail.

Any ideas?
