### ISSUE TITLE
Stuck using version from 9 months ago, can't get latest version to work

### ISSUE THREAD

**Issue by BrodyStone21** [klutchell/unbound-docker#480]
If I update my unbound and try to run it, I get the following error.

```
[1723124195] unbound[1:0] error: could not read root hints /etc/unbound/root.hints: No such file or directory
[1723124195] unbound[1:0] fatal error: Could not set root or stub hints
[1723124198] unbound[1:0] error: could not read root hints /etc/unbound/root.hints: No such file or directory
[1723124198] unbound[1:0] fatal error: Could not set root or stub hints
[1723124201] unbound[1:0] error: could not read root hints /etc/unbound/root.hints: No such file or directory
[1723124201] unbound[1:0] fatal error: Could not set root or stub hints
[1723124204] unbound[1:0] error: could not read root hints /etc/unbound/root.hints: No such file or directory
[1723124204] unbound[1:0] fatal error: Could not set root or stub hints
```

Here is my docker-compose.yml

```
version: '3'

services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image:klutchell/unbound # have also tried klutchell/unbound:main
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/ubuntu/.config/unbound/unbound.conf:/etc/unbound/custom.conf.d/unbound.conf
    network_mode: host
```

I'm using Ubuntu 22.04 LTS x86_64

Any help is apprecaited. I tried fixing this five months ago, but refused to ask for help and eventually gave up. 

I do have a roots.hint file, but I've also tried deleting it. Still doesn't work either way.

**Comment by klutchell** [comment]
Hey, can you share the contents of your custom config as well? Does it work without your custom config?

**Comment by BrodyStone21** [comment]
> Hey, can you share the contents of your custom config as well? Does it work without your custom config?

```
server:
    directory: "/etc/unbound/"

    interface: 0.0.0.0
    port: 5053

    username: "unbound"

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    prefer-ip6: no

    use-caps-for-id: no

    edns-buffer-size: 1232

    aggressive-nsec: yes
    delay-close: 10000
    do-daemonize: no
    do-not-query-localhost: no
    qname-minimisation: yes
    deny-any: yes
    harden-algo-downgrade: yes
    harden-below-nxdomain: yes
    harden-dnssec-stripped: yes
    harden-glue: yes
    harden-large-queries: yes
    harden-short-bufsize: yes
    hide-identity: yes
    hide-version: yes
    identity: "DNS"
    unwanted-reply-threshold: 10000000
    val-clean-additional: yes
    minimal-responses: yes
    prefetch: yes
    prefetch-key: yes
    so-reuseport: yes
    serve-expired: yes

    rrset-cache-size: 250m
    msg-cache-size: 125m
    neg-cache-size: 4M

    num-threads: 8
    msg-cache-slabs: 8
    rrset-cache-slabs: 8
    infra-cache-slabs: 8
    key-cache-slabs: 8

    so-rcvbuf: 4m
    so-sndbuf: 4m

    outgoing-range: 200
    num-queries-per-thread: 100

    access-control: 127.0.0.1/32 allow
    access-control: 192.168.0.0/16 allow
    access-control: 172.16.0.0/12 allow
    access-control: 10.0.0.0/8 allow

    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8

    logfile: ""
    verbosity: 1
    log-local-actions: no
    log-queries: no
    log-replies: no
    log-servfail: no

    root-hints: "/etc/unbound/root.hints"
```

Running without the unbound.conf file produces the following:

```
input in flex scanner failed
input in flex scanner failed
input in flex scanner failed
input in flex scanner failed
```
`ping google.com` produces `Temporary failure in name resolution`

Interestingly enough, this happens no matter what version of the image I'm using. It seems my unbound.conf file is required for operation. I'm running pihole. Does unbound default to port 53? I think it does, so that may be the reason. Perhaps an issue in my config is the culprit. Let me know what you think.

There does appear to be a new folder in my config directory, but no new config file. root.hints, unboundbackup.conf and unbound.conf/ (note that this is a directory, the directory is empty).

**Comment by klutchell** [comment]
I suggest you try reducing your custom config to just the interface and port settings and see if it works with Pi-hole.

The rest of the settings should work with the included defaults and you shouldn't need to re-define them.

**Comment by BrodyStone21** [comment]
> I suggest you try reducing your custom config to just the interface and port settings and see if it works with Pi-hole.

```
server:
    directory: "/etc/unbound/"

    interface: 0.0.0.0
    port: 5053

```

Still produces

```
[1723127959] unbound[1:0] error: could not read root hints root.hints: No such file or directory
[1723127959] unbound[1:0] fatal error: Could not set root or stub hints
[1723127962] unbound[1:0] error: could not read root hints root.hints: No such file or directory
[1723127962] unbound[1:0] fatal error: Could not set root or stub hints
[1723127965] unbound[1:0] error: could not read root hints root.hints: No such file or directory
[1723127965] unbound[1:0] fatal error: Could not set root or stub hints
[1723127968] unbound[1:0] error: could not read root hints root.hints: No such file or directory
[1723127968] unbound[1:0] fatal error: Could not set root or stub hints
[1723127970] unbound[1:0] error: could not read root hints root.hints: No such file or directory
[1723127970] unbound[1:0] fatal error: Could not set root or stub hints
[1723127973] unbound[1:0] error: could not read root hints root.hints: No such file or directory
[1723127973] unbound[1:0] fatal error: Could not set root or stub hints
```

I tried both klutchell/unbound and klutchell/unbound:main

This does work with the old image I have to fall back on.
