### ISSUE TITLE
CacheDB via socket?

### ISSUE THREAD

**Issue by Gontier-Julien** [klutchell/unbound-docker#564]
Hi, i wanted to know if it possible to connect to a redis socket for the CacheDB with this image? Because i can't seem to get it working :/

I always get stuck to:
`error: failed to connect to redis server: No such file or directory`

And i can't seem to figure it out :(
I've tried to change the path where it is or even make the redis socket world readable but nothing is working

The current config of cachedb for unbound:
```
cachedb:
    backend: "redis"
    redis-server-path: "/var/docker/redis.sock"
```
And obviously the redis socket is listening at this path

So if you could help me try to figure it out it would be amazing ^^

**Comment by klutchell** [comment]
Do you have the redis socket mounted in the unbound container? Can you share your compose file or run commands?

**Comment by Gontier-Julien** [comment]
Sorry for the delay,
Here the compose file:

```
services:
  unbound:
    image: ghcr.io/klutchell/unbound:v1.22.0@sha256:bbd1895ec29743901ee110206d62ad39a599eeac50f0c32fdc07ca085ae4e794
    container_name: unbound
    depends_on:
      - valkey
    restart: always
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/zone.conf:/etc/unbound/zone.conf:ro
#      - ./unbound/unbound-rpz.conf:/etc/unbound/rpz/unbound-rpz.conf:ro
      - docker-acme_ssl-certs:/cert:ro,cached
    volumes_from:
      - tmp
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - NET_ADMIN
      - SETGID
      - SETUID
      - SYS_CHROOT

  valkey:
    image: valkey/valkey:8.0.2-alpine@sha256:0fae58181c223280867e8b6d9d5fa29fca507770aeb6819f36d059cab73fa2fd
    container_name: valkey
    user: "1000:1000"
    restart: always
    volumes:
      - ./valkey-data:/data:rw,delegated
      - ./valkey-data/valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
    volumes_from:
      - tmp
    depends_on:
      - tmp
    network_mode: host
    cap_drop:
      - ALL
    command: /usr/local/etc/valkey/valkey.conf
    healthcheck: 
      disable: true

  tmp:
    image: busybox:1.36.1
    command: chmod -R 777 /var/docker
    volumes:
        - /var/docker 

volumes:
  docker-acme_ssl-certs:
    external: true
```

It should be mounted to the container right?
Because i've tried with crazymax unbound image and it working

**Comment by Gontier-Julien** [comment]
@klutchell any news? ^^

**Comment by klutchell** [comment]
Apologies, I'm moving house and haven't had any time to look into this.

Your compose stack looks correct and the socket file should be available to unbound. Perhaps there is a dependency missing to allow unbound to use local files as sockets.

Does it work with https://github.com/MatthewVance/unbound-docker, to rule out something missing in this distroless image?

**Comment by Gontier-Julien** [comment]
Oh alright no problem ! I hope the moving is going well :3!

Yes i did test with the MatthewVance image & crazymax one, and it all work well with it

**Comment by klutchell** [comment]
Sorry for the lack of updates, it's very challenging to investigate and I've been quite busy with my day job.

Can you share your unbound configuration? I see you are mounting a custom one and not using the included defaults.

Are you switching to the `unbound` user in your config with [this](https://github.com/klutchell/unbound-docker/blob/6778afc6d029da7a63a5d6c8c55ba9e8de2be3a6/rootfs_overlay/etc/unbound/unbound.conf#L11) instruction? If so, it might be interesting to remove that and see what happens if you continue to run as root.

Also maybe increase the log levels a bit?

**Comment by Gontier-Julien** [comment]
No worry!

here the current config:

```
server:
    module-config: "respip validator cachedb iterator"
    # Prevent the unbound server from forking into the background as a daemon
    do-daemonize: no

    # Drop user privileges after binding the port.
    username: "unbound"

    # Refuse id.server and hostname.bind queries
    hide-identity: yes
    # Refuse version.server and version.bind queries
    hide-version: yes

    # Do print log lines to inform about local zone actions
    log-local-actions: no
    # Do not print one line per query to the log
    log-queries: no
    # Do not print one line per reply to the log
    log-replies: no
    # Do not print log lines that say why queries return SERVFAIL to clients
    log-servfail: no

    # Sets  logfile  lines to use a timestamp in UTC ascii
    log-time-ascii: yes

    # Prints the destination address, port and type in the log-replies output
    log-destaddr: yes

    # If you want to log to a file, use:
    # Set log location (using /dev/null further limits logging)
    # If "" is given, logging goes to stderr, or nowhere once daemonized.
    logfile: ""
    verbosity: 0

    interface: 0.0.0.0@53
    interface: 0.0.0.0@853
    interface: 0.0.0.0@8080

    do-ip4: yes
    do-tcp: yes
    do-udp: yes

    tls-service-pem: "/cert/fullchain.cer"
    tls-service-key: "/cert/domain.key"
    tls-use-sni: yes

    tls-port: 853

    https-port: 8080
    http-endpoint: /dns-query

    http-nodelay: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/unbound/root.hints"

    # File with trust anchor for one zone, which is tracked with RFC5011 probes.
    # The probes are several times per month, thus the machine must be online frequently.
    # The initial file can be one with contents as described in trust-anchor-file.
    # The file is written to when the anchor is updated, so the unbound user must
    # have write permission.
    auto-trust-anchor-file: "/var/unbound/root.key"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # Fetch the DNSKEYs earlier in the validation process, when a DS record is
    # encountered. This lowers the latency of requests at the expense of little
    # more CPU usage.
    prefetch-key: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    #num-threads: 4
    # 105 - 130ms average
    num-threads: 1

    # Set *-slabs to a power of 2 close to the num-threads value.
    #msg-cache-slabs: 8
    #rrset-cache-slabs: 8
    #infra-cache-slabs: 8
    #key-cache-slabs: 8

    msg-cache-slabs: 1
    rrset-cache-slabs: 1
    infra-cache-slabs: 1
    key-cache-slabs: 1

    # https://nlnetlabs.nl/documentation/unbound/howto-optimise/
    # More cache memory, rrset=msg*2
    #rrset-cache-size: 256m
    #msg-cache-size: 128m
    rrset-cache-size: 128m
    msg-cache-size: 64m

    # RFC 8198. Use the DNSSEC NSEC chain to synthesize NXDO-MAIN and other
    # denials, using information from previous NXDO-MAINs answers. In other
    # words, use cached NSEC records to generate negative answers within a
    # range and positive answers from wildcards. This increases performance,
    # decreases latency and resource utilization on both authoritative and
    # recursive servers, and increases privacy. Also, it may help increase
    # resilience to certain DoS attacks in some circumstances.
    aggressive-nsec: yes

    # Send minimum amount of information to upstream servers to enhance
    # privacy (best privacy).
    qname-minimisation: yes
    #qname-minimisation-strict: yes #Break some domains such as docker

    # Harden against algorithm downgrade when multiple algorithms are
    # advertised in the DS record.
    harden-algo-downgrade: yes

    # RFC 8020. returns nxdomain to queries for a name below another name that
    # is already known to be nxdomain.
    harden-below-nxdomain: yes

    # Harden the referral path by performing additional queries for
    # infrastructure data.  Validates the replies (if possible).
    # Default off, because the lookups burden the server.  Experimental
    # implementation of draft-wijngaards-dnsext-resolver-side-mitigation.
    harden-referral-path: no

    # Will  trust  only  in-zone  glue. Will try to resolve all out of
    # zone (<unverfied>) glue. Will fallback to the original  glue  if
    # unable to resolve.  Default is no.
    harden-unverified-glue: no

    # Restrict the size of DNS responses to prevent certain types of DNS spoofing attacks.
    harden-short-bufsize: yes

    # Do no insert authority/additional sections into response messages when
    # those sections are not required. This reduces response size
    # significantly, and may avoid TCP fallback for some responses. This may
    # cause a slight speedup.
    minimal-responses: yes

    # Help protect users that rely on this validator for authentication from
    # potentially bad data in the additional section. Instruct the validator to
    # remove data from the additional section of secure messages that are not
    # signed properly. Messages that are insecure, bogus, indeterminate or
    # unchecked are not affected.
    val-clean-additional: yes

    # Rotates RRSet order in response (the pseudo-random number is taken from
    # the query ID, for speed and thread safety).
    rrset-roundrobin: yes

    # The time to live (TTL) value cap for RRsets and messages in the
    # cache. Items are not cached for longer. In seconds.
    cache-max-ttl: 86400

    # Increase the TTL for negative responses to reduce 
    # the frequency of expensive NXDOMAIN lookups.
    cache-max-negative-ttl: 3600

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    # (requires CAP_NET_ADMIN or privileged)
    #so-rcvbuf: 4m
    #so-sndbuf: 4m
    so-rcvbuf: 2m
    so-sndbuf: 2m

    # The number of queries that every thread will service simultaneously. If
    # more queries arrive that need servicing, and no queries can be jostled
    # out (see jostle-timeout), then the queries are dropped.
    # This is best set at half the number of the outgoing-range.
    # This Unbound instance was compiled with libevent so it can efficiently
    # use more than 1024 file descriptors.
    #num-queries-per-thread: 4096
    num-queries-per-thread: 512

    # Open dedicated listening sockets for incoming queries for each thread and
    # try to set the SO_REUSEPORT socket option on each socket. May distribute
    # incoming queries to threads more evenly.
    so-reuseport: yes

    # Number of ports to open. This number of file descriptors can be opened
    # per thread.
    # This Unbound instance was compiled with libevent so it can efficiently
    # use more than 1024 file descriptors.
    #outgoing-range: 4096
    # more outgoing connections
    # depends on number of cores: 1024/cores - 50
    outgoing-range: 950

    # Ensure privacy of local IP ranges
    #private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    #private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16

    # If  null or "", no file is used.  Set it to the certificate bun-
    # dle file, for example "/etc/pki/tls/certs/ca-bundle.crt".  These
    # certificates  are  used  for  authenticating connections made to
    # outside peers.  For example auth-zone urls, and  also  DNS  over
    # TLS  connections.  It is read at start up before permission drop
    # and chroot.
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

	# Serve expired responses from cache, with serve-expired-reply-ttl in
	# the response, and then attempt to fetch the data afresh.
	serve-expired: no

	# Limit serving of expired responses to configured seconds after
	# expiration. 0 disables the limit.
    # A suggested value per RFC 8767 is between 86400 (1 day) and 259200 (3 days).
    #serve-expired-ttl: 86400

    # Time in milliseconds before replying to the client with expired data
    # A recommended value per RFC 8767 is 1800
    #serve-expired-client-timeout: 0

    # Return the original TTL as received from the upstream name server rather
	# than the decrementing TTL as stored in the cache.  Enabling this feature
	# does not impact cache expiry, it only changes the TTL Unbound embeds in
	# responses to queries. Note that enabling this feature implicitly disables
	# enforcement of the configured minimum and maximum TTL.
	#serve-original-ttl: yes

    access-control: 0.0.0.0/0 allow

rpz:
    name: blocklist-all.txt
    url: http://127.52.0.2:4000/blocklist-all.txt
    #rpz-action-override: nxdomain

# ^(.+)((?:\r?\n.*)*)\r?\n\1$
cachedb:
    backend: "redis"
    redis-server-host: 127.52.0.1
    redis-server-port: 6378
    redis-server-password: "redacted"
    redis-expire-records: yes
    redis-timeout: 500

remote-control:
    control-enable: no
    control-use-cert: no
```

I'll try this weekend if i have time removing the unbound username, also obviously the cachedb backend is as my first comment here when i was testing.
I think i've removed the unbound username when i was testing, can't remember honestly sorry

Did you by any change got it working maybe with another config?

**Comment by Gontier-Julien** [comment]
Hi, sorry for the lack of update, thing has been very busy.
So i've just tried without the `unbound` user, and it didn't change anything

**Comment by klutchell** [comment]
I was able to reproduce it locally, and I was able to solve it by making sure the socket was owned by UID `101:102`.

I'm working on a minimal example now.

**Comment by klutchell** [comment]
This minimal setup worked for me

**valkey.conf**
```
dir /data

unixsocket /var/valkey/valkey.sock
# unixsocketgroup 102
unixsocketperm 777
```

**rootfs_overlay/etc/unbound/custom.conf.d/cachedb.conf.example**
```
server:
  module-config: "validator cachedb iterator"

cachedb:
  backend: "redis"
  redis-server-path: "/var/valkey/valkey.sock"
  redis-expire-records: yes
```

**docker-compose.yml**
```yaml
services:
  server:
    image: ghcr.io/klutchell/unbound:v1.22.0@sha256:bbd1895ec29743901ee110206d62ad39a599eeac50f0c32fdc07ca085ae4e794
    volumes:
      # enable cachedb example configuration file
      - ./rootfs_overlay/etc/unbound/custom.conf.d/cachedb.conf.example:/etc/unbound/custom.conf.d/cachedb.conf:ro
    container_name: unbound
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - NET_ADMIN
      - SETGID
      - SETUID
      - SYS_CHROOT
    depends_on:
      - valkey
    volumes_from:
      - valkey

# https://hub.docker.com/r/valkey/valkey/
  valkey:
    image: valkey/valkey:8.0.2-alpine@sha256:0fae58181c223280867e8b6d9d5fa29fca507770aeb6819f36d059cab73fa2fd
    container_name: valkey
    # user: "101:102"
    restart: always
    tmpfs:
      - /data
    volumes:
      - ./valkey/valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
      - valkey-var:/var/valkey
    # cap_drop:
    #   - ALL
    # command:
    #   - valkey-server
    #   - /usr/local/etc/valkey/valkey.conf
    healthcheck: 
      disable: true
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        chmod 777 /var/valkey
        sh -x /usr/local/bin/docker-entrypoint.sh /usr/local/etc/valkey/valkey.conf

volumes:
  valkey-var: {}
```

**Comment by Gontier-Julien** [comment]
Do you think it possible to do it without building the container? :(

**Comment by klutchell** [comment]
Oh yes, my mistake, I only had that line because I was testing with an alpine container to inspect permissions. I have updated the example compose file. No modifications are needed to the unbound image.

The main change is having valkey create the socket with 777 permissions, and not relying on the sidecar container to update the permissions. Also having valkey run as root (0) because UID 1000 was not recognized by the unbound container.

**Comment by Gontier-Julien** [comment]
Okay maybe i'll need to test everything with exactly everything like you have but still no luck on my side

Here the setup on my side without your modification:

Unbound.conf

```
server:
    module-config: "respip validator cachedb iterator"
    # Prevent the unbound server from forking into the background as a daemon
    do-daemonize: no

    # Drop user privileges after binding the port.
    username: "unbound"

    # Refuse id.server and hostname.bind queries
    hide-identity: yes
    # Refuse version.server and version.bind queries
    hide-version: yes

    # Do print log lines to inform about local zone actions
    log-local-actions: no
    # Do not print one line per query to the log
    log-queries: no
    # Do not print one line per reply to the log
    log-replies: no
    # Do not print log lines that say why queries return SERVFAIL to clients
    log-servfail: no

    # Sets  logfile  lines to use a timestamp in UTC ascii
    log-time-ascii: yes

    # Prints the destination address, port and type in the log-replies output
    log-destaddr: yes

    # If you want to log to a file, use:
    # Set log location (using /dev/null further limits logging)
    # If "" is given, logging goes to stderr, or nowhere once daemonized.
    logfile: ""
    verbosity: 0

    interface: 0.0.0.0@53
    interface: ::0@53
    interface: 0.0.0.0@853
    interface: ::0@853
    interface: 0.0.0.0@8080
    interface: ::0@8080

    do-ip4: yes
    do-tcp: yes
    do-udp: yes

    tls-service-pem: "/cert/fullchain.cer"
    tls-service-key: "/cert/ssl.key"
    tls-use-sni: yes

    tls-port: 853

    https-port: 8080
    http-endpoint: /dns-query

    http-nodelay: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: yes

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: yes

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/unbound/root.hints"

    # File with trust anchor for one zone, which is tracked with RFC5011 probes.
    # The probes are several times per month, thus the machine must be online frequently.
    # The initial file can be one with contents as described in trust-anchor-file.
    # The file is written to when the anchor is updated, so the unbound user must
    # have write permission.
    auto-trust-anchor-file: "/var/unbound/root.key"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # Fetch the DNSKEYs earlier in the validation process, when a DS record is
    # encountered. This lowers the latency of requests at the expense of little
    # more CPU usage.
    prefetch-key: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    #num-threads: 4
    # 105 - 130ms average
    num-threads: 1

    # Set *-slabs to a power of 2 close to the num-threads value.
    #msg-cache-slabs: 8
    #rrset-cache-slabs: 8
    #infra-cache-slabs: 8
    #key-cache-slabs: 8

    msg-cache-slabs: 1
    rrset-cache-slabs: 1
    infra-cache-slabs: 1
    key-cache-slabs: 1

    # https://nlnetlabs.nl/documentation/unbound/howto-optimise/
    # More cache memory, rrset=msg*2
    #rrset-cache-size: 256m
    #msg-cache-size: 128m
    rrset-cache-size: 128m
    msg-cache-size: 64m

    # RFC 8198. Use the DNSSEC NSEC chain to synthesize NXDO-MAIN and other
    # denials, using information from previous NXDO-MAINs answers. In other
    # words, use cached NSEC records to generate negative answers within a
    # range and positive answers from wildcards. This increases performance,
    # decreases latency and resource utilization on both authoritative and
    # recursive servers, and increases privacy. Also, it may help increase
    # resilience to certain DoS attacks in some circumstances.
    aggressive-nsec: yes

    # Send minimum amount of information to upstream servers to enhance
    # privacy (best privacy).
    qname-minimisation: yes
    #qname-minimisation-strict: yes #Break some domains such as docker

    # Harden against algorithm downgrade when multiple algorithms are
    # advertised in the DS record.
    harden-algo-downgrade: yes

    # RFC 8020. returns nxdomain to queries for a name below another name that
    # is already known to be nxdomain.
    harden-below-nxdomain: yes

    # Harden the referral path by performing additional queries for
    # infrastructure data.  Validates the replies (if possible).
    # Default off, because the lookups burden the server.  Experimental
    # implementation of draft-wijngaards-dnsext-resolver-side-mitigation.
    harden-referral-path: no

    # Will  trust  only  in-zone  glue. Will try to resolve all out of
    # zone (<unverfied>) glue. Will fallback to the original  glue  if
    # unable to resolve.  Default is no.
    harden-unverified-glue: no

    # Restrict the size of DNS responses to prevent certain types of DNS spoofing attacks.
    harden-short-bufsize: yes

    # Do no insert authority/additional sections into response messages when
    # those sections are not required. This reduces response size
    # significantly, and may avoid TCP fallback for some responses. This may
    # cause a slight speedup.
    minimal-responses: yes

    # Help protect users that rely on this validator for authentication from
    # potentially bad data in the additional section. Instruct the validator to
    # remove data from the additional section of secure messages that are not
    # signed properly. Messages that are insecure, bogus, indeterminate or
    # unchecked are not affected.
    val-clean-additional: yes

    # Rotates RRSet order in response (the pseudo-random number is taken from
    # the query ID, for speed and thread safety).
    rrset-roundrobin: yes

    # The time to live (TTL) value cap for RRsets and messages in the
    # cache. Items are not cached for longer. In seconds.
    cache-max-ttl: 86400

    # Increase the TTL for negative responses to reduce 
    # the frequency of expensive NXDOMAIN lookups.
    cache-max-negative-ttl: 3600

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    # (requires CAP_NET_ADMIN or privileged)
    #so-rcvbuf: 4m
    #so-sndbuf: 4m
    so-rcvbuf: 2m
    so-sndbuf: 2m

    # The number of queries that every thread will service simultaneously. If
    # more queries arrive that need servicing, and no queries can be jostled
    # out (see jostle-timeout), then the queries are dropped.
    # This is best set at half the number of the outgoing-range.
    # This Unbound instance was compiled with libevent so it can efficiently
    # use more than 1024 file descriptors.
    #num-queries-per-thread: 4096
    num-queries-per-thread: 512

    # Open dedicated listening sockets for incoming queries for each thread and
    # try to set the SO_REUSEPORT socket option on each socket. May distribute
    # incoming queries to threads more evenly.
    so-reuseport: yes

    # Number of ports to open. This number of file descriptors can be opened
    # per thread.
    # This Unbound instance was compiled with libevent so it can efficiently
    # use more than 1024 file descriptors.
    #outgoing-range: 4096
    # more outgoing connections
    # depends on number of cores: 1024/cores - 50
    outgoing-range: 950

    # Ensure privacy of local IP ranges
    #private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    #private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16

    # If  null or "", no file is used.  Set it to the certificate bun-
    # dle file, for example "/etc/pki/tls/certs/ca-bundle.crt".  These
    # certificates  are  used  for  authenticating connections made to
    # outside peers.  For example auth-zone urls, and  also  DNS  over
    # TLS  connections.  It is read at start up before permission drop
    # and chroot.
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

	# Serve expired responses from cache, with serve-expired-reply-ttl in
	# the response, and then attempt to fetch the data afresh.
	serve-expired: no

	# Limit serving of expired responses to configured seconds after
	# expiration. 0 disables the limit.
    # A suggested value per RFC 8767 is between 86400 (1 day) and 259200 (3 days).
    #serve-expired-ttl: 86400

    # Time in milliseconds before replying to the client with expired data
    # A recommended value per RFC 8767 is 1800
    #serve-expired-client-timeout: 0

    # Return the original TTL as received from the upstream name server rather
	# than the decrementing TTL as stored in the cache.  Enabling this feature
	# does not impact cache expiry, it only changes the TTL Unbound embeds in
	# responses to queries. Note that enabling this feature implicitly disables
	# enforcement of the configured minimum and maximum TTL.
	#serve-original-ttl: yes

    access-control: 0.0.0.0/0 allow
    access-control: ::1 allow

    include: /etc/unbound/zone.conf

rpz:
    name: blocklist-all.txt
    url: http://[::1]:4000/blocklist-all.txt
    #rpz-action-override: nxdomain

# ^(.+)((?:\r?\n.*)*)\r?\n\1$
cachedb:
    backend: "redis"
    #redis-server-host: ::1
    #redis-server-port: 6379
    redis-server-path: "/var/valkey/valkey.sock"
    redis-expire-records: yes
    redis-timeout: 500

remote-control:
    control-enable: no
    control-use-cert: no
```

Valkey is exactly as you have so no change here

And the docker compose file:

```
services:
  unbound:
#    image: ghcr.io/klutchell/unbound:v1.22.0@sha256:bbd1895ec29743901ee110206d62ad39a599eeac50f0c32fdc07ca085ae4e794
    image: ghcr.io/klutchell/unbound:v1.23.0@sha256:17ea6e14cfed57506c9db69686eb4de665056a342922727f3a6bbea50be184e4
    container_name: unbound
    restart: always
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/zone.conf:/etc/unbound/zone.conf:ro
#      - ./unbound/unbound-rpz.conf:/etc/unbound/rpz/unbound-rpz.conf:ro
      - docker-acme_ssl-certs:/cert:ro,cached
    network_mode: host
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - NET_ADMIN
      - SETGID
      - SETUID
      - SYS_CHROOT
    cpus: "1"
    cpuset: "0"
    mem_limit: "2g"
    depends_on:
      - valkey
    volumes_from:
      - valkey

  valkey:
#    image: valkey/valkey:8.1.0-alpine@sha256:7c1426974c5f80e5aa510eb6dc6d699f103a302e095afcf3babe9fe6b7076ee6
    image: valkey/valkey:8.1.1-alpine@sha256:f3959d30d4aa6df4fe7468c6b17d103e56f0fc7a4246f32d8106991b3665cdb9
    container_name: valkey
    #user: "1000:1000"
    restart: always
    tmpfs:
      - /data
    volumes:
      #- ./valkey-data:/data:rw,delegated
      - ./valkey-data/valkey.conf:/usr/local/etc/valkey/valkey.conf:ro
      - valkey-var:/var/valkey
    network_mode: host
    #cap_drop:
    #  - ALL
    #command: /usr/local/etc/valkey/valkey.conf
    healthcheck: 
      disable: true
    cpus: "1"
    cpuset: "0"
    mem_limit: "20m"
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        chmod 777 /var/valkey
        sh -x /usr/local/bin/docker-entrypoint.sh /usr/local/etc/valkey/valkey.conf

volumes:
  valkey-var: {}
  docker-acme_ssl-certs:
    external: true
```

And still got:

```
Jun 05 21:13:52 unbound[1:0] error: failed to connect to redis server: No such file or directory
Jun 05 21:13:52 unbound[1:0] error: redis_init: failed to init redis (for thread 0)
Jun 05 21:13:52 unbound[1:0] info: start of service (unbound 1.23.0).
Jun 05 21:13:52 unbound[1:0] error: failed to connect to redis server: No such file or directory
Jun 05 21:13:52 unbound[1:0] error: failed to connect to redis server: No such file or directory
Jun 05 21:13:52 unbound[1:0] error: failed to connect to redis server: No such file or directory
Jun 05 21:13:52 unbound[1:0] error: failed to connect to redis server: No such file or directory
```

**Comment by Gontier-Julien** [comment]
Just tested with you compose etc, same issue still :/

**Comment by klutchell** [comment]
If you replace the unbound server container with a generic alpine container, can you inspect the mounted socket and confirm the permissions and ownership?

That's how I iterated in testing, I took the unbound container out of the equation until I got the permissions on the socket to look like this in the alpine container.
```
server-1  | drwxrwxrwx    2 root     root          4096 Jun  6 16:56 .
server-1  | drwxr-xr-x    1 root     root          4096 Jun  6 16:56 ..
server-1  | srwxrwxrwx    1 999      1000             0 Jun  6 16:56 valkey.sock
```
Where 999 and 1000 are the default UID/GID in the valkey container. When the socket looks like that, and the unbound config matches the settings shipped with this container, plus the overlay I specified above, it works for me.

If your socket permissions look different when unbound is replaced with alpine, then we need to focus there.

**Comment by Gontier-Julien** [comment]
I sure have the good permissions and the socket exist:

```
drwxrwxrwx    2 999      1000             3 Jun  6 17:28 .
drwxr-xr-x    1 root     root             3 Jun  6 17:28 ..
srwxrwxrwx    1 999      1000             0 Jun  6 17:28 valkey.sock
```

**Comment by klutchell** [comment]
Okay good, now if you use the config we are shipping with this unbound container, and only mount this overlay config to `/etc/unbound/custom.conf.d/cachedb.conf:ro` then we will have the same unbound config as well.

```
server:
  module-config: "validator cachedb iterator"

cachedb:
  backend: "redis"
  redis-server-path: "/var/valkey/valkey.sock"
  redis-expire-records: yes
```
So try not mounting your own config file, just the custom.conf.d file and nothing else to isolate the differences between our setups.
