### ISSUE TITLE
Permission errors on 1.16.0 version

### ISSUE THREAD

**Issue by dajul** [klutchell/unbound-docker#67]
Hello,

docker container keeps restarting after bumping from version 1.15.0 to 1.16.0 due to permission errors:

```
unbound  | [1654542108] unbound[1:0] notice: init module 0: validator
unbound  | [1654542108] unbound[1:0] notice: init module 1: iterator
unbound  | [1654542108] unbound[1:0] info: start of service (unbound 1.16.0).
unbound  | [1654542108] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN
unbound  | [1654542108] unbound[1:0] fatal error: could not open autotrust file for writing, /etc/unbound/root.key.1-0-7f3acc3b5810: Permission denied
```

I could reproduce it on another host, always using Ubuntu 22.04 as host OS.
Start container with `klutchell/unbound:1.15.0` and update it to `klutchell/unbound:1.16.0`

docker-compose.yml :

```
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    environment:
      DNS1: 172.30.0.254
      DNS2: 172.30.0.254
      WEBPASSWORD: mysecretpassword
      #PH_VERBOSE: 1
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 81:80/tcp
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    networks:
      default: null
    restart: unless-stopped

  unbound:
    image: klutchell/unbound:1.15.0
    container_name: unbound
    hostname: unbound
    volumes:
       - config:/etc/unbound
    networks:
      default:
        ipv4_address: 172.30.0.254
    restart: unless-stopped

volumes:
  config: {}
  pihole: {}
  dnsmasq: {}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
```

Going back to `klutchell/unbound:1.15.0` image works perfectly.

Thank you!
