### ISSUE TITLE
Having trouble getting root.hints file to work properly

### ISSUE THREAD

**Issue by BrodyStone21** [klutchell/unbound-docker#91]
I downloaded the root.hints file and entered the path in unbound.conf. I'm now receiving the following error. 

```
[1661205444] unbound[1:0] info: start of service (unbound 1.16.2).
[1661205444] unbound[1:7] error: second hints for zone . ignored.
[1661205444] unbound[1:6] error: second hints for zone . ignored.
[1661205444] unbound[1:2] error: second hints for zone . ignored.
```

Any help would be appreciated. The only thing I could find on this repo related to root.hints was pulling it before manually building the container. 

Everything is working fine, but it's driving me a bit crazy, because I don't know if I did this correctly. 

Docker run command

```
docker run -d \
  --name=unbound \
  --net=host \
  --restart=unless-stopped \
  -v /home/ubuntu/.config/unbound/unbound.conf:/etc/unbound/custom.conf.d/unbound.conf \
  -v /home/ubuntu/.config/unbound/root.hints:/var/lib/root.hints \
  --cap-add=NET_ADMIN \
  klutchell/unbound:latest
```

unbound.conf

```
server:
    directory: "/etc/unbound/"

    interface: 0.0.0.0
    port: 5053

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    prefer-ip6: no

    harden-glue: yes
    harden-dnssec-stripped: yes

    use-caps-for-id: no

    edns-buffer-size: 1232

    prefetch: yes
    serve-expired: yes
    serve-expired-ttl: 86400

    rrset-cache-size: 250m
    msg-cache-size: 125m

    num-threads: 8
    msg-cache-slabs: 8
    rrset-cache-slabs: 8
    infra-cache-slabs: 8
    key-cache-slabs: 8

    so-rcvbuf: 4m
    so-sndbuf: 4m

    outgoing-range: 200
    num-queries-per-thread: 100

    private-address: 192.168.0.0/16

    verbosity: 0

    logfile: ""

    root-hints: "/var/lib/root.hints"
```

**Comment by klutchell** [comment]
Hey @BrodyStone21, how did you download the root hints? Can you confirm the contents look the same as [this](https://raw.githubusercontent.com/klutchell/unbound-docker/main/rootfs_overlay/etc/unbound/root.hints)?

**Comment by BrodyStone21** [comment]
> Hey @BrodyStone21, how did you download the root hints? Can you confirm the contents look the same as [this](https://raw.githubusercontent.com/klutchell/unbound-docker/main/rootfs_overlay/etc/unbound/root.hints)?

Hello, I'm sorry for the late reply. I followed the steps in the documentation and the contents look the same. 

Anything else I can provide?

**Comment by klutchell** [comment]
Can you make sure that your root hints file is readable by `101:102` or world?

What if you change the root hints mount and config path to `/etc/unbound/root.hints`?

**Comment by BrodyStone21** [comment]
> Can you make sure that your root hints file is readable by `101:102` or world?
> 
> What if you change the root hints mount and config path to `/etc/unbound/root.hints`?

Running `sudo chown 101:102 root.hints` and `sudo chmod +rwx root.hints` did not work. I forgot I changed my compose since posting this. Here is what I'm currently working with. As you can see, I'm already using `/etc/unbound/root.hints`

```
version: '3'

services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image: klutchell/unbound
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/ubuntu/.config/unbound/unbound.conf:/etc/unbound/custom.conf.d/unbound.conf
      - /home/ubuntu/.config/unbound/root.hints:/etc/unbound/root.hints
    network_mode: host
```

You can tell Unbound is reading the root.hints file because if I move the root.hints file and `touch root.hints`, then start Unbound, I receive the following error. 

```
[1663680832] unbound[1:2] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:4] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:3] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:4] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:1] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:2] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:3] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:1] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:5] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:0] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:5] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:0] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:7] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:0] info: start of service (unbound 1.16.2).
[1663680832] unbound[1:6] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:7] warning: root hints /etc/unbound/root.hints: no NS content
[1663680832] unbound[1:6] warning: root hints /etc/unbound/root.hints: no NS content
```
